### ISSUE TITLE
Display skill description

### ISSUE THREAD

**Issue by richarddewit** [ralrom/tl2-calculator#1]
Can you make it so that the Description of the skills are displayed on mouseover? They are already present in the JSON file so it's just a matter of showing some kind of box for it.
Can you make this, or would you like a PR for it?

If the latter applies, would you mind telling me what the whole Mailman Module is does?

**Comment by ralrom** [comment]
I can add it in the next few days, it shouldn't take too long. I had this feature before I rewrote the javascript that's why the descriptions are there but not used.

PR: the mailman module is used by all the other modules to allow them to communicate with each other. It's similar to event listeners in a way. The code is messy though.

**Comment by ralrom** [comment]
Added the skill descriptions. It's not perfect but it'll work for now

**Comment by richarddewit** [comment]
Awesome, well done! :+1:
